# tasks file
---
- name: configure | create directories
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - dest: "{{ autossh_tunnel_client_configuration_directory }}"
      mode: '0700'
    - dest: "{{ autossh_tunnel_client_autossh_pidfile | dirname }}"
      mode: '0755'
  tags:
    - autossh-tunnel-client-configure-directories
    - autossh-tunnel-client-configure-directories-create

- name: configure | update configuration file(s)
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ autossh_tunnel_client_etc_default_file.lstrip('/') }}.j2"
      dest: "{{ autossh_tunnel_client_etc_default_file }}"
      mode: '0644'
    - src: "{{ autossh_tunnel_client_install_prefix.lstrip('/') }}/autossh-tunnel-client-wrapper.j2"
      dest: "{{ autossh_tunnel_client_install_prefix }}/autossh-tunnel-client-wrapper"
      mode: '0755'
  notify: restart autossh-tunnel-client
  tags:
    - autossh-tunnel-client-configure-configuration

- name: configure | copy key file(s)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    remote_src: "{{ item.remote_src | default(omit) }}"
    dest: "{{ autossh_tunnel_client_configuration_directory }}/{{ item.dest | default(item.src | basename) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default(item.owner) | default('root') }}"
    mode: "{{ item.mode | default('0600') }}"
  with_items: "{{ autossh_tunnel_client_key_map }}"
  notify: restart autossh-tunnel-client
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-configuration
    - autossh-tunnel-client-configuration-keys
