# tasks file for autossh-tunnel-client
---
- name: facts | set
  set_fact:
     is_docker_guest: "{{ ansible_virtualization_role | default('host') == 'guest' and ansible_virtualization_type | default('none') == 'docker' }}"
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-facts

- name: install package
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ autossh_tunnel_client_dependencies }}"
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-install

- include: configure.yml
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-configure

- block:
    - include: service-initd.yml
  when: is_docker_guest
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-service
    - autossh-tunnel-client-service-initd

- block:
    - include: service-upstart.yml
      when: ansible_service_mgr != 'systemd'
      tags:
        - autossh-tunnel-client-service-upstart

    - include: service-systemd.yml
      when: ansible_service_mgr == 'systemd'
      tags:
        - autossh-tunnel-client-service-systemd
  when: not is_docker_guest
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-service

- name: start and enable service
  service:
    name: autossh-tunnel-client
    state: started
    enabled: true
  tags:
    - configuration
    - autossh-tunnel-client
    - autossh-tunnel-client-start-enable-service
