# tasks file
---
- name: service | upstart | update script
  ansible.builtin.template:
    src: "{{ autossh_tunnel_client_etc_init_file.lstrip('/') }}.j2"
    dest: "{{ autossh_tunnel_client_etc_init_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart autossh-tunnel-client
  tags:
    - autossh-tunnel-client-service-upstart-update
