# tasks file for autossh-tunnel-client
---
- name: service | upstart | update script
  template:
    src: etc/init/autossh-tunnel-client.conf.j2
    dest: /etc/init/autossh-tunnel-client.conf
    owner: root
    group: root
    mode: 0644
  notify: restart autossh-tunnel-client
  tags:
    - autossh-tunnel-client-service-upstart-update
