# tasks file for autossh-tunnel-client
---
- name: service | systemd | update script
  template:
    src: "{{ autossh_tunnel_client_etc_systemd_file.lstrip('/') }}.j2"
    dest: "{{ autossh_tunnel_client_etc_systemd_file }}"
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart autossh-tunnel-client
  tags:
    - autossh-tunnel-client-service-systemd-update

- name: service | systemd | reload
  systemd:
    daemon_reload: true
  when: _update_systemd_script is changed
  tags:
    - autossh-tunnel-client-service-systemd-reload
