# handlers file for autossh-tunnel-client
---
- name: restart autossh-tunnel-client
  service:
    name: autossh-tunnel-client
    state: restarted
  when: service_default_state | default('started') == 'started'
