# handlers file
---
- name: restart autossh-tunnel-client
  ansible.builtin.service:
    name: autossh-tunnel-client
    state: restarted
  when: service_default_state | default('started') == 'started'
