---
- name: Prepare
  hosts: all
  become: true
  pre_tasks:
    - name: include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
    - name: include tasks
      ansible.builtin.include: "{{ playbook_dir }}/../../tests/tasks/pre.yml"
